Alt+u cycle video-unscaled

Alt+d set speed 1.5
] multiply speed 1.0594630943592953
[ multiply speed 0.9438743126816935

Alt+o show-text "apc=${audio-pitch-correction} af=${af}"
Alt+p cycle-values audio-pitch-correction yes no; cycle-values af "@rb:rubberband=engine=finer" ""

Alt+x af-command rb multiply-pitch 1.0594630943592953; show-text "Pitch: +1"
Alt+y af-command rb multiply-pitch 0.9438743126816935; show-text "Pitch: -1"
