# Player
border=no
fs=yes
#fs-screen=0
keep-open=yes
msg-color=yes
msg-module=yes
save-position-on-quit

# Video
vo=gpu-next
gpu-api=vulkan
gpu-context=x11vk
hwdec=nvdec-copy
hwdec-codecs=all

deband=no
deinterlace=no
interpolation=no
#tscale=oversample
vd-lavc-dr=yes
vd-lavc-bitexact
hr-seek-framedrop=no

scale=ewa_lanczossharp
cscale=ewa_lanczos
cscale-blur=1.015
dscale=mitchell

hdr-peak-percentile=99.995
hdr-contrast-recovery=0.30

video-aspect-override=no
#video-unscaled=yes
#keepaspect=yes
#keepaspect-window=yes
#monitoraspect=16:9

# Audio
ao=alsa
#audio-device=alsa/e30-safe
audio-channels=stereo
audio-pitch-correction=no
audio-file-auto=fuzzy

# Subtitle
sub-auto=fuzzy

# Screenshot
screenshot-format=png
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes
screenshot-directory=~/Pictures
screenshot-png-compression=5
screenshot-sw=no
