# Player
border=no
fs=yes
#fs-screen=0
keep-open=yes
msg-color=yes
msg-module=yes
save-position-on-quit

# Video
vo=gpu-next
gpu-api=vulkan
gpu-context=x11vk
hwdec=nvdec-copy
hwdec-codecs=all

deband=no
deinterlace=no
interpolation=no
#tscale=oversample
vd-lavc-dr=yes
vd-lavc-bitexact
hr-seek-framedrop=no

scale=ewa_lanczossharp
cscale=ewa_lanczos
cscale-blur=1.015
dscale=mitchell

hdr-peak-percentile=99.995
hdr-contrast-recovery=0.30

video-aspect-override=no
#video-unscaled=yes
#keepaspect=yes
#keepaspect-window=yes
#monitoraspect=16:9

# Audio
volume=50
ao=alsa
#ao=pipewire
#audio-device=alsa/hw_board
audio-device=alsa/hw_e30
audio-exclusive=yes
audio-resample=no
audio-channels=stereo
audio-pitch-correction=no
audio-file-auto=fuzzy
#af=lavfi=[volume=volume=-6.4dB,bass=f=20:g=1:w=0.71:t=q,equalizer=f=68:t=q:w=0.6:g=-2,bass=f=105:g=5.5:w=0.71:t=q,equalizer=f=300:t=q:w=1:g=-0.7,equalizer=f=1100:t=q:w=1.7:g=-2,equalizer=f=1950:t=q:w=1:g=6.6,equalizer=f=3000:t=q:w=1.7:g=-5.9,equalizer=f=5000:t=q:w=6:g=-2,equalizer=f=7000:t=q:w=2:g=-2.5,treble=f=10000:g=-1:w=0.71:t=q]

# Subtitle
sub-auto=fuzzy

# Screenshot
screenshot-format=png
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes
screenshot-directory=~/Pictures
screenshot-png-compression=5
screenshot-sw=no
